version: "3.8"

services:
  mysqldb1:
    container_name: mysqldb1
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: MYSQL
      MYSQL_DB: testautomation
      MYSQL_ROOT_PASSWORD: MYSQL
    ports:
      - 3308:3306
    volumes:
      - mysql_data_volume:/var/lib/mysql
    networks:
      - springboot-mysql-net2

  springboot-container2:
    container_name: springboot-container2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb1
    environment:
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
      - spring.datasource.url=jdbc:mysql://mysqldb1:3306/testautomation
      - spring.datasource.username=root
      - spring.datasource.password=MYSQL
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
    networks:
      - springboot-mysql-net2
    restart: on-failure

networks:
  springboot-mysql-net2:
    driver: bridge

volumes:
  mysql_data_volume:
